//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookOrder
    {
        public int ID { get; set; }
        public Nullable<int> ID_Book { get; set; }
        public Nullable<int> ID_Order { get; set; }
        public Nullable<int> ID_From { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual From From { get; set; }
        public virtual Order Order { get; set; }
    }
}
